
set COLOR_RESET=[0m
set COLOR_RED=[31m
set COLOR_GREEN=[32m
set COLOR_YELLOW=[33m
set COLOR_BLUE=[34m
set COLOR_MAGENTA=[35m
set COLOR_LBLUE=[36m

set COLOR_BRED=[101m
set COLOR_BBLUE=[104m

set COLOR_HEADING1=%COLOR_GREEN%
set COLOR_WARNING=%COLOR_MAGENTA%
set COLOR_ERROR=%COLOR_RED%
