#!/bin/bash

COLOR_RESET="\e[0m"
COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_BLUE="\e[34m"
COLOR_MAGENTA="\e[35m"
COLOR_LBLUE="\e[36m"

COLOR_BRED="\e[101m"
COLOR_BBLUE="\e[104m"

COLOR_HEADING1=$COLOR_GREEN
COLOR_WARNING=$COLOR_MAGENTA
COLOR_ERROR=$COLOR_RED
